### ISSUE TITLE
Se documenter et voir ce qui se fait

### ISSUE THREAD

**Issue by unkn0wn107** [unkn0wn107/webserv#1]
La doc de base, on peut déjà se dire de prendre connaissance de ca d'ici le début de la semaine prochaine.
Sans forcement rentrer dans tous les détails mais au moins d'avoir couvert ca en diagonale.

**[LE Sujet](https://cdn.intra.42.fr/pdf/pdf/127222/fr.subject.pdf)**

**Une bonne ref (MDN)** : https://developer.mozilla.org/fr/docs/Web/HTTP

**La norme : HTTP/1.1bis** : [Résumé des RFCs en FR](https://github.com/users/unkn0wn107/projects/1/views/1?pane=issue&itemId=59602484). Doc originale : [RFC7230](https://datatracker.ietf.org/doc/html/rfc7230), [RFC7231](https://datatracker.ietf.org/doc/html/rfc7231), [RFC7232](https://datatracker.ietf.org/doc/html/rfc7232), [RFC7233](https://datatracker.ietf.org/doc/html/rfc7233), [RFC7234](https://datatracker.ietf.org/doc/html/rfc7234) et [RFC7235](https://datatracker.ietf.org/doc/html/rfc7235)

**Un bon article avec un petit MVP implémenté en c++ : [Building an http server (Article)](https://osasazamegbe.medium.com/showing-building-an-http-server-from-scratch-in-c-2da7c0db6cb7)**

**Parsing**
- https://medium.com/swlh/toy-browser-http-request-and-response-parse-bc4476c14628
- https://dev.to/bennyxguo/learn-how-the-browser-works-in-practice-http-request-and-parsing-4fdg

**Design pattern**
- Factory : https://refactoring.guru/design-patterns/factory-method

**Comment by lmohin** [comment]
RFC pour les cookies : [RFC6265](https://datatracker.ietf.org/doc/html/rfc6265)
